import { DEFAULT_CATEGORIES, DEFAULT_MERCHANT_RULES } from '../packages/shared/src/constants';

export const SEED_USER = {
  id: 'user_demo_1',
  email: 'kailash@example.com',
  name: 'Kailash',
  monthlyIncome: 120000,
  currency: 'INR',
};

export const SEED_ACCOUNTS = [
  {
    id: 'acc_hdfc_salary',
    userId: SEED_USER.id,
    name: 'HDFC Salary Account',
    type: 'SALARY',
    bank: 'HDFC',
    accountNumberMasked: 'HDFC ****4321',
    currentBalance: 82300,
    openingBalance: 50000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_sbi_savings',
    userId: SEED_USER.id,
    name: 'SBI Emergency Savings',
    type: 'SAVINGS',
    bank: 'SBI',
    accountNumberMasked: 'SBI ****8901',
    currentBalance: 35000,
    openingBalance: 25000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_icici_cc',
    userId: SEED_USER.id,
    name: 'ICICI Amazon Pay Credit Card',
    type: 'CREDIT_CARD',
    bank: 'ICICI',
    accountNumberMasked: 'ICICI ****6789',
    currentBalance: -14200,
    openingBalance: 0,
    creditLimit: 200000,
    availableLimit: 185800,
    statementDate: 15,
    dueDate: 5,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_cash_hand',
    userId: SEED_USER.id,
    name: 'Cash in Hand',
    type: 'CASH',
    accountNumberMasked: 'CASH',
    currentBalance: 4500,
    openingBalance: 5000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_zerodha_mf',
    userId: SEED_USER.id,
    name: 'Zerodha Coin (Mutual Funds)',
    type: 'INVESTMENT',
    bank: 'OTHER',
    accountNumberMasked: 'ZERODHA ****1122',
    currentBalance: 320000,
    openingBalance: 250000,
    currency: 'INR',
    isActive: true,
  },
];

export const SEED_DEBTS = [
  {
    id: 'debt_car_loan',
    userId: SEED_USER.id,
    name: 'Car Loan (Hyundai Creta)',
    lender: 'HDFC Bank',
    type: 'CAR_LOAN',
    originalAmount: 800000,
    outstandingAmount: 425000,
    interestRate: 8.5,
    monthlyEmi: 18500,
    startDate: '2024-06-05',
    endDate: '2028-06-05',
    dueDay: 5,
    notes: 'Auto-debit from HDFC Salary A/c on 5th of every month',
  },
];

export const SEED_GOALS = [
  {
    id: 'goal_bank_balance',
    userId: SEED_USER.id,
    name: 'Keep ₹1,00,000 in Bank Account',
    category: 'BANK_BALANCE',
    targetAmount: 100000,
    currentAmount: 82300,
    targetDate: '2026-10-31',
    monthlyContribution: 10000,
    isCompleted: false,
    notes: 'Liquid buffer in primary salary account',
  },
  {
    id: 'goal_emergency_fund',
    userId: SEED_USER.id,
    name: '6-Month Emergency Cushion',
    category: 'EMERGENCY_FUND',
    targetAmount: 270000,
    currentAmount: 120000,
    targetDate: '2027-06-30',
    monthlyContribution: 15000,
    isCompleted: false,
    notes: 'Parked in SBI Savings + High Yield Liquid FDs',
  },
  {
    id: 'goal_buy_car',
    userId: SEED_USER.id,
    name: 'Electric SUV Purchase',
    category: 'VEHICLE_CAR',
    targetAmount: 800000,
    currentAmount: 200000,
    targetDate: '2028-12-31',
    monthlyContribution: 20000,
    isCompleted: false,
    notes: 'Down payment and initial accessory costs',
  },
  {
    id: 'goal_buy_bike',
    userId: SEED_USER.id,
    name: 'Superbike (Kawasaki / Triumph)',
    category: 'VEHICLE_BIKE',
    targetAmount: 400000,
    currentAmount: 125000,
    targetDate: '2027-08-31',
    monthlyContribution: 15000,
    isCompleted: false,
    notes: 'Weekend touring machine & riding gear',
  },
  {
    id: 'goal_house_downpayment',
    userId: SEED_USER.id,
    name: 'House Down Payment (Bangalore)',
    category: 'HOUSE_PURCHASE',
    targetAmount: 2000000,
    currentAmount: 350000,
    targetDate: '2030-03-31',
    monthlyContribution: 25000,
    isCompleted: false,
    notes: 'Long term down payment fund in Index Mutual Funds',
  },
];

export const SEED_BUDGET = {
  id: 'budget_2026_09',
  userId: SEED_USER.id,
  month: '2026-09',
  totalAmount: 77000,
  items: [
    { id: 'bi_1', budgetId: 'budget_2026_09', categoryId: 'cat_housing', amount: 20000 },
    { id: 'bi_2', budgetId: 'budget_2026_09', categoryId: 'cat_financial', amount: 18500 },
    { id: 'bi_3', budgetId: 'budget_2026_09', categoryId: 'cat_food', amount: 15000 },
    { id: 'bi_4', budgetId: 'budget_2026_09', categoryId: 'cat_family', amount: 8000 },
    { id: 'bi_5', budgetId: 'budget_2026_09', categoryId: 'cat_transport', amount: 6000 },
    { id: 'bi_6', budgetId: 'budget_2026_09', categoryId: 'cat_utilities', amount: 5500 },
    { id: 'bi_7', budgetId: 'budget_2026_09', categoryId: 'cat_healthcare', amount: 4000 },
  ],
};

export const SEED_RECURRING = [
  {
    id: 'rec_salary',
    userId: SEED_USER.id,
    name: 'Tech Employer Monthly Salary',
    amount: 120000,
    type: 'INCOME',
    frequency: 'MONTHLY',
    categoryId: 'cat_income',
    subcategoryId: 'sub_salary',
    accountId: 'acc_hdfc_salary',
    startDate: '2026-01-01',
    dueDay: 1,
    isActive: true,
  },
  {
    id: 'rec_rent',
    userId: SEED_USER.id,
    name: 'Flat Rent',
    amount: 20000,
    type: 'EXPENSE',
    frequency: 'MONTHLY',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_rent',
    accountId: 'acc_hdfc_salary',
    startDate: '2026-01-01',
    dueDay: 2,
    isActive: true,
  },
  {
    id: 'rec_car_emi',
    userId: SEED_USER.id,
    name: 'Car Loan EMI',
    amount: 18500,
    type: 'DEBT_PAYMENT',
    frequency: 'MONTHLY',
    categoryId: 'cat_financial',
    subcategoryId: 'sub_emi_car',
    accountId: 'acc_hdfc_salary',
    startDate: '2024-06-05',
    dueDay: 5,
    isActive: true,
  },
  {
    id: 'rec_sip',
    userId: SEED_USER.id,
    name: 'Nifty 50 Index SIP',
    amount: 15000,
    type: 'INVESTMENT',
    frequency: 'MONTHLY',
    categoryId: 'cat_investment',
    subcategoryId: 'sub_sip',
    accountId: 'acc_hdfc_salary',
    startDate: '2025-01-10',
    dueDay: 10,
    isActive: true,
  },
  {
    id: 'rec_wifi',
    userId: SEED_USER.id,
    name: 'Airtel Broadband Wi-Fi',
    amount: 1179,
    type: 'EXPENSE',
    frequency: 'MONTHLY',
    categoryId: 'cat_utilities',
    subcategoryId: 'sub_wifi',
    accountId: 'acc_hdfc_salary',
    startDate: '2026-01-15',
    dueDay: 15,
    isActive: true,
  },
  {
    id: 'rec_milk',
    userId: SEED_USER.id,
    name: 'Country Delight Milk Subscription',
    amount: 1800,
    type: 'EXPENSE',
    frequency: 'MONTHLY',
    categoryId: 'cat_food',
    subcategoryId: 'sub_milk',
    accountId: 'acc_hdfc_salary',
    startDate: '2026-01-01',
    dueDay: 1,
    isActive: true,
  },
];

export const SEED_TRANSACTIONS = [
  // September 2026 Transactions (Current Month)
  {
    id: 'tx_sep_01',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_income',
    subcategoryId: 'sub_salary',
    date: '2026-09-01',
    description: 'NEFT CR-TECH SOLUTIONS CORP-SALARY FOR AUG',
    merchantName: 'Tech Employer',
    amount: 120000,
    type: 'INCOME',
    paymentMethod: 'NEFT',
    source: 'BANK_PDF',
    referenceNumber: 'NEFT202609010012',
    balanceAfter: 135400,
    notes: 'Monthly salary credited',
  },
  {
    id: 'tx_sep_02',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_rent',
    date: '2026-09-02',
    description: 'UPI-RENT SEPTEMBER-LANDLORD@OKSBI',
    merchantName: 'Landlord Rent',
    amount: -20000,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'BANK_PDF',
    referenceNumber: 'UPI6245890123',
    balanceAfter: 115400,
    notes: '2BHK Apartment Rent',
  },
  {
    id: 'tx_sep_03',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_food',
    subcategoryId: 'sub_milk',
    date: '2026-09-02',
    description: 'UPI-COUNTRY DELIGHT MILK RECHARGE',
    merchantName: 'Country Delight',
    amount: -1800,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'MANUAL',
    referenceNumber: 'UPI6245890125',
    balanceAfter: 113600,
    notes: 'Monthly organic milk delivery package',
  },
  {
    id: 'tx_sep_04',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_financial',
    subcategoryId: 'sub_emi_car',
    date: '2026-09-05',
    description: 'ACH DR-HDFC LOAN 9876543-EMI AUTO DEBIT',
    merchantName: 'HDFC Car Loan',
    amount: -18500,
    type: 'DEBT_PAYMENT',
    paymentMethod: 'AUTO_DEBIT',
    source: 'BANK_PDF',
    referenceNumber: 'ACH202609050089',
    balanceAfter: 95100,
    notes: 'Car EMI (Principal + Interest)',
  },
  {
    id: 'tx_sep_05',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_food',
    subcategoryId: 'sub_groceries',
    date: '2026-09-05',
    description: 'POS 4123 DMART SUPERMARKET BANGALORE',
    merchantName: 'DMart',
    amount: -4650,
    type: 'EXPENSE',
    paymentMethod: 'DEBIT_CARD',
    source: 'BANK_PDF',
    referenceNumber: 'POS99887711',
    balanceAfter: 90450,
    notes: 'Monthly staples, spices, rice and dry groceries',
  },
  {
    id: 'tx_sep_06',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_transport',
    subcategoryId: 'sub_petrol',
    date: '2026-09-06',
    description: 'UPI-HPCL PETROL PUMP WHITEFIELD',
    merchantName: 'HPCL Petrol Pump',
    amount: -2500,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'MANUAL',
    referenceNumber: 'UPI6245890987',
    balanceAfter: 87950,
    notes: 'Full tank petrol',
  },
  {
    id: 'tx_sep_07',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_food',
    subcategoryId: 'sub_delivery',
    date: '2026-09-07',
    description: 'UPI-ZOMATO-ORDER 998822@OKHDFC',
    merchantName: 'Zomato',
    amount: -420,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'MANUAL',
    referenceNumber: 'UPI6245891100',
    balanceAfter: 87530,
    notes: 'Dinner with family',
  },
  {
    id: 'tx_sep_08',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_utilities',
    subcategoryId: 'sub_electricity',
    date: '2026-09-07',
    description: 'UPI-BESCOM ELECTRICITY BILL BANGALORE',
    merchantName: 'BESCOM',
    amount: -1850,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'MANUAL',
    referenceNumber: 'UPI6245891188',
    balanceAfter: 85680,
    notes: 'August power consumption bill',
  },
  {
    id: 'tx_sep_09',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_family',
    subcategoryId: 'sub_wife_personal',
    date: '2026-09-07',
    description: 'UPI-WIFE PERSONAL EXPENSES-ANANYA@OKSBI',
    merchantName: 'Ananya (Wife)',
    amount: -5000,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'MANUAL',
    referenceNumber: 'UPI6245891255',
    balanceAfter: 80680,
    notes: 'Monthly personal allowance',
  },

  // August 2026 Transactions (Previous Month)
  {
    id: 'tx_aug_01',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_income',
    subcategoryId: 'sub_salary',
    date: '2026-08-01',
    description: 'NEFT CR-TECH SOLUTIONS CORP-SALARY FOR JUL',
    merchantName: 'Tech Employer',
    amount: 120000,
    type: 'INCOME',
    paymentMethod: 'NEFT',
    source: 'BANK_PDF',
    referenceNumber: 'NEFT202608010044',
  },
  {
    id: 'tx_aug_02',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_rent',
    date: '2026-08-02',
    description: 'UPI-RENT AUGUST-LANDLORD@OKSBI',
    merchantName: 'Landlord Rent',
    amount: -20000,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_03',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_financial',
    subcategoryId: 'sub_emi_car',
    date: '2026-08-05',
    description: 'ACH DR-HDFC LOAN 9876543-EMI AUTO DEBIT',
    merchantName: 'HDFC Car Loan',
    amount: -18500,
    type: 'DEBT_PAYMENT',
    paymentMethod: 'AUTO_DEBIT',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_04',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_food',
    subcategoryId: 'sub_groceries',
    date: '2026-08-06',
    description: 'POS 4123 DMART SUPERMARKET',
    merchantName: 'DMart',
    amount: -4800,
    type: 'EXPENSE',
    paymentMethod: 'DEBIT_CARD',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_05',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_food',
    subcategoryId: 'sub_milk',
    date: '2026-08-02',
    description: 'UPI-COUNTRY DELIGHT MILK RECHARGE',
    merchantName: 'Country Delight',
    amount: -1800,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_06',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_transport',
    subcategoryId: 'sub_petrol',
    date: '2026-08-10',
    description: 'BPCL PETROL PUMP KORAMANGALA',
    merchantName: 'BPCL Petrol Pump',
    amount: -3200,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_07',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_investment',
    subcategoryId: 'sub_sip',
    date: '2026-08-10',
    description: 'ACH DR-ZERODHA BROKING LTD-SIP',
    merchantName: 'Zerodha Coin SIP',
    amount: -15000,
    type: 'INVESTMENT',
    paymentMethod: 'AUTO_DEBIT',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_08',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_family',
    subcategoryId: 'sub_shopping',
    date: '2026-08-14',
    description: 'AMAZON PAY INDIA MUMBAI',
    merchantName: 'Amazon',
    amount: -3400,
    type: 'EXPENSE',
    paymentMethod: 'CREDIT_CARD',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_09',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    categoryId: 'cat_utilities',
    subcategoryId: 'sub_wifi',
    date: '2026-08-15',
    description: 'AIRTEL FIBER BROADBAND',
    merchantName: 'Airtel Broadband',
    amount: -1179,
    type: 'EXPENSE',
    paymentMethod: 'UPI',
    source: 'BANK_PDF',
  },
  {
    id: 'tx_aug_10',
    userId: SEED_USER.id,
    accountId: 'acc_hdfc_salary',
    toAccountId: 'acc_sbi_savings',
    categoryId: 'cat_transfer',
    subcategoryId: 'sub_acc_transfer',
    date: '2026-08-18',
    description: 'IMPS/TRANSFER TO SBI SAVINGS',
    merchantName: 'Self Transfer',
    amount: -10000,
    type: 'TRANSFER',
    paymentMethod: 'IMPS',
    source: 'BANK_PDF',
  },
];
